### ISSUE TITLE
Analyse and Tal would like the Twitter sentiment training data

### ISSUE THREAD

**Issue by rtanglao** [turtlelovesshoes/SUMOTwitterInsights#12]
Hi @benmiroglio & @turtlelovesshoes 

Analyse and Ta (@havardl and  Cecilie Astrupgard, sorry Cecilie i couldn't find your github id!) would like the twitter sentiment training data.

Could you please provide it in this issue?

.

**Comment by benmiroglio** [comment]
We used two public datasets:

https://www.kaggle.com/kazanova/sentiment140
https://github.com/pollockj/world_mood/blob/master/sts_gold_v03/sts_gold_tweet.csv

**Comment by rtanglao** [comment]
awesome thanks @benmiroglio ! closing
